### ISSUE TITLE
The setup script failed

### ISSUE THREAD

**Issue by XiangcaiHuang** [openthread/borderrouter#125] opened 2017-12-17 11:42 UTC
I used the latest code, but the script always failed and show the following log:
...
Connection 'BorderRouter-AP' (9e68a65d-ba48-437b-9630-90d75916baba) successfully added.
...
Connection 'BorderRouter-Eth' (e20bda30-0d90-442d-abaf-70eb6d4b4316) successfully added.
Error: Timeout 90 sec expired.

**Comment by bukepo** [comment] 2017-12-18 04:37
Hi, could you please give more details on the environment? For example, the hardware platform, the OS and so on?

**Comment by XiangcaiHuang** [comment] 2017-12-18 09:06
Hi, bukepo
I used the Raspi 3B and Raspbian Stretch Lite, version: 2017-09-07
I've run script "./script/bootstrap" from "borderrouter" directory, it worked fine. But it always failed when I run script "./script/setup" and show the above timeout error. 
I found there was something wrong after "create_eth_connection" in the script "./script/_network_manager":
```
network_manager_install()
{...
create_eth_connection
    sudo systemctl daemon-reload
    sudo systemctl restart NetworkManager
    sleep 15
    if [ $PLATFORM = raspbian ]; then
        sudo nmcli c up ${AP_CONN}
    fi
    sudo nmcli c up ${ETH_CONN}
}
```
Did I miss something?

**Comment by XiangcaiHuang** [comment] 2017-12-18 12:19
Hi, bukepo
I've sloved this problem just now. Thanks for your reply!
I found the network-manager will setup a wifi AP named "BorderRouter-AP" and I can access the web UI. Well, what should I do next? Do I still need to configure the Pi step by step following the official document: [Wi-Fi Access Point Setup for OpenThread Border Router](https://openthread.io/guides/border_router/access_point)
In addition, I found the Border Router with NCP(Nordic nRF52840) is not able to talk with my Thread Nodes(Synopsys EMSK, Nordic nRF52840 and my custom board). No matter who create a Thread Network, the NCP or the Thread Nodes, there is nothing after I executing the command "scan". But it works fine between the Thread Nodes.
What's more, I've tried that only install wpantund on the Pi, and everything is OK using the wpanctl, such as "scan", "join" and so on. But I use the wpantund(Tags: full/latest-release Version: 0.07.01 (0.07.01-2-g6993264; Dec 11 2017 14:03:19)) at that time. Does the different version of wpantund make difference?

> pi@raspberrypi:~ $ sudo wpanctl status
> wpan0 => [
> 	"NCP:State" => "offline"
> 	"Daemon:Enabled" => true
> 	"NCP:Version" => "OPENTHREAD/0.01.00; ARM Mbed; Dec 18 2017 18:55:32"
> 	"Daemon:Version" => "0.08.00d (/120ef3e; Dec 18 2017 10:17:31)"
> 	"Config:NCP:DriverName" => "spinel"
> 	"NCP:HardwareAddress" => [0050C2FFFE1D3000]
> ]

> pi@raspberrypi:~ $ sudo wpanctl -I wpan0 scan
>    | Joinable | NetworkName        | PAN ID | Ch | XPanID           | HWAddr           | RSSI
> ---+----------+--------------------+--------+----+------------------+------------------+------

> pi@raspberrypi:~ $ ifconfig
> nat64: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
>         inet 192.168.255.1  netmask 255.255.255.255  destination 192.168.255.1
>         inet6 fdaa:bb:1::1  prefixlen 128  scopeid 0x0<global>
>         inet6 fe80::25b2:fb31:9d61:8a1b  prefixlen 64  scopeid 0x20<link>
>         unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 4  bytes 304 (304.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.42.0.1  netmask 255.255.255.0  broadcast 10.42.0.255
>         inet6 fe80::ba27:ebff:fea2:7b3  prefixlen 64  scopeid 0x20<link>
>         ether b8:27:eb:a2:07:b3  txqueuelen 1000  (Ethernet)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 31  bytes 5354 (5.2 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> wpan0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
>         unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
>         RX packets 0  bytes 0 (0.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 4  bytes 384 (384.0 B)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by bukepo** [comment] 2017-12-18 13:36
Could you please write the steps to reproduce this issue? And please also attach the syslog of your respberry pi.
I’m wondering if the NCP is working normally.

**Comment by jobroe** [comment] 2018-01-05 17:12
I encountered the same problem. The script "./script/bootstrap" from "borderrouter" directory, it worked fine for me as well. But it failed when I run script "./script/setup" with the following:
Current platform is raspbian
sudo-timeout: Not extending, Disabled
Swapfile: not required
Failed to stop otbr-web.service: Unit otbr-web.service not loaded.
Failed to stop otbr-agent.service: Unit otbr-agent.service not loaded.
Failed to stop wpantund.service: Unit wpantund.service not loaded.
Failed to disable unit: No such file or directory
Failed to get unit file state for otbr-web.service: No such file or directory
Failed to get unit file state for otbr-agent.service: No such file or directory
Failed to get unit file state for wpantund.service: No such file or directory
otbr-web: no process found
otbr-agent: no process found
inactive
Error: 'BorderRouter-AP' is not an active connection.
Error: no active connection provided.
Error: unknown connection 'BorderRouter-AP'.
Error: cannot delete unknown connection(s): 'BorderRouter-AP'.
Error: 'BorderRouter-Eth' is not an active connection.
Error: no active connection provided.
Error: unknown connection 'BorderRouter-Eth'.
Error: cannot delete unknown connection(s): 'BorderRouter-Eth'.
rm: cannot remove '/etc/NetworkManager/dispatcher.d/ap-helper': No such file or directory
rm: cannot remove '/etc/NetworkManager/dispatcher.d/dhcpv6-helper': No such file or directory
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable dhcpcd
Failed to disable unit: No such file or directory
Failed to stop ncp_state_notifier.service: Unit ncp_state_notifier.service not loaded.
rm: cannot remove '/etc/systemd/system/ncp_state_notifier.service': No such file or directory
rm: cannot remove '/usr/sbin/ncp_state_notifier': No such file or directory
rm: cannot remove '/etc/ncp_state_notifier/dispatcher.d/dhcpcd_reloader': No such file or directory
rm: cannot remove '/etc/default/wpantund': No such file or directory
rm: cannot remove '/etc/ncp_state_notifier/dispatcher.d': No such file or directory
mv: cannot stat '/etc/dhcpcd.conf.orig': No such file or directory
inactive
active
wpantund: no process found
otbr-nat44.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable otbr-nat44
disabled
enabled
Synchronizing state of bind9.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable bind9
removed '/etc/sysctl.d/60-otbr-ip-forward.conf'
net.ipv6.conf.all.forwarding = 1
net.ipv4.ip_forward = 1
#! /bin/sh
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
### BEGIN INIT INFO
# Provides:          otbr-nat44
# Required-Start:    tayga
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: iptables NAT44
# Description:       NAT44 is require for OpenThread border router
#                    to connect to arbitrary IPv4 endpoints.
### END INIT INFO

. /lib/lsb/init-functions
. /lib/init/vars.sh

case "$1" in
    start)
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop|status)
        # No-op
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
otbr-nat44.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable otbr-nat44
Synchronizing state of bind9.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable bind9
enabled
disabled
enabled
Removed /etc/systemd/system/multi-user.target.wants/wpa_supplicant.service.
Removed /etc/systemd/system/dbus-fi.epitest.hostap.WPASupplicant.service.
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable dhcpcd
Removed /etc/systemd/system/dhcpcd5.service.
Created symlink /etc/systemd/system/multi-user.target.wants/NetworkManager.service → /lib/systemd/system/NetworkManager.service.
Created symlink /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service → /lib/systemd/system/NetworkManager-dispatcher.service.
#!/bin/sh
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

NAME="ap-helper"

IFNAME=$1
ACTION=$2

AP_CONN="BorderRouter-AP"

DHCP_START="10.42.0.2"
DHCP_END="10.42.0.8"

ROUTER_IP="10.42.0.1"

DNS1=${ROUTER_IP}
DNS2="8.8.8.8"


log()
{
    logger -t "${NAME}[${$}]" $*
}

disable_accept_ra()
{
    log "Disable accepting Router Advertisements on the interface: '${IFNAME}'"
    sysctl -w net.ipv6.conf.${IFNAME}.accept_ra=1
}

start_dnsmasq()
{
    log "Starting 'dnsmasq' on the interface: '${IFNAME}'"
    /usr/sbin/dnsmasq -i ${IFNAME} -a ${ROUTER_IP} -b -z -K -F${DHCP_START},${DHCP_END},24h -p0 -O3,${ROUTER_IP} -O6,${DNS1},${DNS2}
}

kill_dnsmasq()
{
    local DNSMASQ_PID=`pidof dnsmasq`

    if [ -n ${DNSMASQ_PID} ]; then
        log "Killing 'dnsmasq' process with PID: '${DNSMASQ_PID}'"
        kill -9 ${DNSMASQ_PID}
    else
        log "'dnsmasq' is not running"
    fi
}

release_dhcpcd()
{
    log "Releasing 'dhcpcd' on the interface: '${IFNAME}'"
    /sbin/dhcpcd -6 -k ${IFNAME}
}

handle_action_up()
{
    case ${IFNAME} in
    wlan*)
        if [ ${CONNECTION_ID} = ${AP_CONN} ]; then
            release_dhcpcd
            disable_accept_ra
            start_dnsmasq
        fi
        ;;
    *)
        ;;
    esac
}

handle_action_down()
{
    case ${IFNAME} in
    wlan*)
        if [ ${CONNECTION_ID} = ${AP_CONN} ]; then
            kill_dnsmasq
        fi
        ;;
    *)
        log "Skipping action: '${ACTION}' on the interface: '${IFNAME}'"
        ;;
    esac
}


case ${ACTION} in
up)
    handle_action_up
    ;;
down)
    handle_action_down
    ;;
*)
    log "Unsupported action: '${ACTION}'"
    ;;
esac
Error: invalid <setting>.<property> 'BorderRouter-AP'.

**Comment by bukepo** [comment] 2018-01-06 01:26
Could you please check the output of
```sh
nmcli d | grep wifi | cut -d" " -f1
```
It seems no wifi interface was found.

**Comment by jobroe** [comment] 2018-01-06 10:30
I'm sorry for your effort. Unfortunatlly I have noticed that the RPI which I was using is a RPI version 2. I'll get one of version 3 B and try it again.
I'm wondering why a wifi interface is required since the beaglebone has also no. Is it also possible to use the RPI 2 if you do without the WIFI Accespoint? In case if it is possible, it would be nice if you could provide some hints at which points the setup script has to be modified. 

Thanks a lot !

**Comment by bukepo** [comment] 2018-01-07 02:50
I think you may try disabling network_manager by setting `NETWORK_MANAGER=0` in https://github.com/openthread/borderrouter/blob/master/examples/platforms/raspbian/default

**Comment by jobroe** [comment] 2018-01-11 20:21
It seems not enough to get it working on RPI2. But for me it doesn't matter anymore I got my RPI3 and with this device it is working. Only one thing, it was necessary to execute the setup script as root , otherwise permission denied errors occur. 
Thanks !

**Comment by XiangcaiHuang** [comment] 2018-01-13 08:25
Thanks a lot. All the scripts worked fine for me now.
But I encountered another problem. My OTBR has been built and installed successfully on a raspi 3B runing Stretch. Then start a Thread device as a leader and created a Thread network using CLI commands.
On the raspi, type ''sudo wpanctl scan", the Thread network could not be found.
How can I solve the problem?
How can I debug the OTBR? Are there log files or other tools?

**Comment by HendraWijaya** [comment] 2018-04-03 01:03
I'm experiencing same problem as OP. I've followed the instruction:
https://openthread.io/guides/border_router/raspberry_pi_3b 
I'm using RPI3 and running Raspbian Stretch Lite OS image. Any fix for this?

**Comment by jwhui** [comment] 2018-04-16 22:33
@HendraWijaya, are you still having issues with this?

I just tested and the scripts seem to work for me.

Hardware version:
```
$ cat /proc/cpuinfo
...
Revision        : a22082
```

Linux is [Raspbian Stretch Lite 2018-03-13](https://www.raspberrypi.org/downloads/raspbian/).
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by HendraWijaya** [comment] 2018-04-20 02:12
@jwhui I tried again and it works now. I connect the pi through eth. It didn't work before because I connected through wlan.

**Closed** 2018-06-29 07:59 UTC

**Comment by tarunsmalviya** [comment] 2018-09-17 07:47
@XiangcaiHuang 
Hi!
I am also facing same Timeout error issue. Can you please mention how you resolved it.

**Comment by XiangcaiHuang** [comment] 2018-09-29 01:32
@tarunsmalviya 
Hi, I'm sorry for the late reply. Have you solved the problem?
I was just trying to run the script at different times of the day, then it finally work. So it maybe the reason for the network connection but I'm not sure.
