### ISSUE TITLE
Cannot connect commissioner app with OTBR

### ISSUE THREAD

**Issue by ubx-caloca** [openthread/borderrouter#176] opened 2018-08-21 18:58 UTC
Since recent commits on both openthread/openthread and openthread/borderrouter, I cannot get the commissioning app to connect with the OTBR.  Just tried today with latest commits from openthread (8/21/2018) and borderrouter (8/18/2018) and still cannot connect.

I'm tried with two boards as NCP, a TI CC2652 and a TI CC2538. Both with the firmware generated with "Makefile-cc2538 BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_PROXY=1".

I can form a Thread network without a problem, connect with a smartphone to the  BR's AP wifi, open the commissioning app and see the border router in the list. However when I click on the border router so that I can establish a connection and type the commissioner passphrase is where the problem occurs, it's a little different for the CC2652 and for the CC2538.

For the CC2652, if I type "wpanctl status" just when the commissioning app is trying to connect (after clicking on the BR and before it shows the enter the commissioner passphrase dialog) the wpanctl command takes a while to reply. After 5-10 seconds the NCP:State becomes "Uninitialized" then "Uninitialized:fault", the commissioner passphrase dialog appears in the commissioning app but even if I type the correct passphrase I get an "incorrect password" error message in the app.

For the CC2538, if I type "wpanctl status" just when the commissioning app is trying to connect the wpanctl command takes 5-10 seconds to reply. After a few seconds the NCP:State still continues in the "associated" state", then the commissioner passphrase dialog appears in the commissioning app but even if I type the correct passphrase I get an "incorrect password" error message in the app.

I'm attaching the syslogs of both CC2652 and CC2538 when this happens. Has anyone encountered this issue recently? Around one month ago I was using the commissioning app without any issues with both these boards.  

[errorCommissionerCC2538.txt](https://github.com/openthread/borderrouter/files/2307654/errorCommissionerCC2538.txt)
[errorCommissionerCC2652.txt](https://github.com/openthread/borderrouter/files/2307655/errorCommissionerCC2652.txt)

**Comment by jwhui** [comment] 2018-08-22 00:48
@ubx-caloca, thanks for raising this issue. Were you able to get things working with a previous commit?

**Comment by bukepo** [comment] 2018-08-22 12:47
I can reproduce this issue and I'm still debugging this. I will update when I find the root cause.

**Comment by ubx-caloca** [comment] 2018-08-22 17:05
@jwhui I will try getting back to a working commit in both OTBR and the stack later today. @bukepo  good to know that you are getting to the root cause, thanks.

**Comment by bukepo** [comment] 2018-08-23 04:34
@ubx-caloca @jwhui 
Update: I found the received bytes are different from wpantund sent, which resulted in HDLC parse error. I think this might be an issue similar to openthread/openthread#2857. And I also verified that there's no such issue with nrf52840 board. I guess this is a UART driver issue. Any thoughts?

**Comment by ubx-caloca** [comment] 2018-08-23 20:43
@jwhui @bukepo I tried to go back in time in both openthread/openthread and openthread/borderrouter, specifically return to jun 26 on both, to see if the issue is not there. I did a clean installation of the OTBR. I was sure that it was working fine at that time, however, I was still unable to connect the commissioning app with the BR, its taking a long time for the passphrase dialog to appear, then after typing it, I'm getting the incorrect passphrase message. I'm attaching the syslog when I try to connect the comm app with the OTBR in case it help you in any way.

@bukepo Do you want me to test the OTBR with the current commits form OTBR and OT stack?

**Comment by leonsteenkamp** [comment] 2018-08-28 19:45
hey, I think have run into this issue now too. Using CC2652 as NCP.

**Comment by jwhui** [comment] 2018-08-28 20:00
@leonsteenkamp, thanks for reporting. Were you able to get something working and stable with an earlier commit on the cc2652?

**Comment by leonsteenkamp** [comment] 2018-08-28 20:27
@jwhui nope, I have just recently started my Thread journey and have yet to get a working setup. I was stuck for a bit because the CLI for cc2652 was broken (didn't see any output form the UART) until a recent commit (I think). I was following the guides from the start again and got to this point. I then saw this issue which describes what I am seeing.

**Comment by bukepo** [comment] 2018-08-29 07:52
The debugging result shows cc2538 receives some incomplete HDLC packets. Currently, the example code doesn't enable hardware accelerated encryption for cc2538. When cc2538 is computing the ECC keys, it cannot handle bytes in UART, so those bytes get overwritten by new data. I think we have two solutions:

1. Enable hardware encryption
2. Involve a background task mechanism and put key calculation at background so that it will not block other operations.

@srickardti @jwhui what do you think?

**Comment by leonsteenkamp** [comment] 2018-09-05 16:28
@bukepo Hi, I am assuming that the two options you mention are non-trivial to implement?

**Comment by bukepo** [comment] 2018-09-06 03:40
@leonsteenkamp from the data sheet of CC2538, it seems it has versions supporting hardware accelerated AES and ECP. But I didn't find much material about it.

**Comment by srickardti** [comment] 2018-09-06 16:59
Hardware acceleration seems to be the bottleneck. While testing the next [SIMPLELINK-CC26X2-SDK](http://www.ti.com/tool/SIMPLELINK-CC26X2-SDK) I didn't have any issue with commissioning.

@leonsteenkamp neither would be trivial to implement. A back-grounding feature for the tasklets would introduce a bit of complexity that might fail conformance testing. And implementing hardware acceleration without the TI-RTOS driver is a bit of work. 

I've added the feature request to support PKA hardware acceleration for the CC13X2/CC26X2 in this repository.

@bukepo the best example of using the PKA in the CC2538 will be in the [CC2538 foundation firmware](http://www.ti.com/tool/CC2538-SW). You could also look at the implementation of EC-JPAKE in the SimpleLink SDK, I've been told the IP for the PKA is very close for the CC13X2/CC26X2 family and the CC2538.

**Comment by bukepo** [comment] 2018-09-10 05:01
@leonsteenkamp if you want to use chip without hardware acceleration. I suggest you try the newly added [posix-app](https://github.com/openthread/openthread/pull/3052), which offloads most computing onto Linux, so that there should not be the hardware acceleration issue on the NCP side any more.

**Comment by bukepo** [comment] 2018-09-10 05:02
@srickardti Thanks for the information.

**Comment by srickardti** [comment] 2018-09-24 15:38
@bukepo Yes, that will work for now.

We'll add hardware acceleration for the CC13X2/CC26X2 sometime in the future.

**Closed** 2018-10-25 03:59 UTC

**Comment by rohithanayady** [comment] 2021-06-04 07:25
It take long time ,5-10 minutes for adding a new device to the thread network using Thread Commissioning app.What will be the reason and how it rectify?

**Comment by jwhui** [comment] 2021-06-04 19:22
> It take long time ,5-10 minutes for adding a new device to the thread network using Thread Commissioning app.What will be the reason and how it rectify?

@rohithanayady , I opened #879 for you.
