### ISSUE TITLE
Wlan interface instead of Ethernet in border router 

### ISSUE THREAD

**Issue by bahubalioffice67** [openthread/borderrouter#231] opened 2019-01-16 12:27 UTC
**Is your feature request related to a problem? Please describe.**
Since our office doesn't have IPV6 network, i would like to use wifi adpater to get get IPV6 on raspberry pi.

**Describe the solution you'd like**
I have connected tp-link n600 wifi adpter to pi board and modified below script
 file: ./script/_network_manager

AP_CONN="BorderR-AP"
ETH_CONN="random1"

create_ap_connection()
{
    IFNAME=$(nmcli d | grep wlan0 | cut -d" " -f1)
    sudo nmcli c add type wifi ifname $IFNAME con-name ${AP_CONN} ssid ${AP_CONN}
    sudo nmcli c modify ${AP_CONN} 802-11-wireless.mode ap 802-11-wireless.band bg ipv4.method shared ipv6.method ignore
    sudo nmcli c modify ${AP_CONN} wifi-sec.key-mgmt wpa-psk
    sudo nmcli c modify ${AP_CONN} wifi-sec.proto rsn
    sudo nmcli c modify ${AP_CONN} wifi-sec.psk "12345678"
}

create_eth_connection()
{
    IFNAME=$(nmcli d | grep wlan1 | cut -d" " -f1)
    sudo nmcli c add type wifi ifname $IFNAME con-name "random1" ssid "random1"
    sudo nmcli c modify "random1" wifi-sec.key-mgmt wpa-psk
    sudo nmcli c modify "random1" wifi-sec.psk "12345678"
}

set WAN_INTERFACE="wlan1 " in _dhcpv6_pd file.
set WLAN_IFNAMES=wlan1  in _nat64 file.

With above modification I am able to run "./script/setup" successfully and able to see ipv6 on wlan1.
But not able to see global ip on wpan0. Should i make any other modifications to get global ip for wpan0?

**Comment by jwhui** [comment] 2019-01-16 12:31
Discussion on [openthread-users](https://groups.google.com/d/msg/openthread-users/v1ZM2r09s8Q/g0vyZvZoCAAJ)

**Comment by jwhui** [comment] 2019-01-16 12:33
I am not able to reproduce the issue on a clean setup of OTBR. Are the global IPv6 addresses reflected on `wpan0` interface if you **do not** make the changes to `script/_network_manager`?

**Comment by bahubalioffice67** [comment] 2019-01-16 12:34
> Discussion on [openthread-users](https://groups.google.com/d/msg/openthread-users/v1ZM2r09s8Q/g0vyZvZoCAAJ)

Basically I have 2 question
1. Using wlan instead of Ethernet in border router
2. NCP is not updating wpan0 with proper ipv6 and prefix

**Comment by bahubalioffice67** [comment] 2019-01-16 12:37
> I am not able to reproduce the issue on a clean setup of OTBR. Are the global IPv6 addresses reflected on `wpan0` interface if you **do not** make the changes to `script/_network_manager`?

I don't have IPV6 on Ethernet. When I connect Ethernet(only ipv4) I am able to see only mesh and link local  addresses.

**Comment by jwhui** [comment] 2019-01-16 12:40
You don't need IPv6 on Ethernet for Thread IPv6 addresses to be reflect on `wpan0` interface. If you are seeing mesh-local addresses on the `wpan0` interface, it seems that the NCP is updating `wpan0` properly.

**Comment by bahubalioffice67** [comment] 2019-01-17 05:09
@jwhui 
With Ethernet(ipv4) also mesh local address is not reflecting on wpan0.

Correct me if I am wrong: I want to communicate thread end node "globally" via border router. i.e, thread end node acts as coap server and it is being communicated globally via some client(some PC). For this I need to have IPV6 on border router isn't it?That is reason I am trying to have ipv6 on border router.

**Comment by jwhui** [comment] 2019-01-17 08:46
For global connectivity:

- If you want end-to-end IPv6 communication, then you need IPv6 on the WAN interface.

- If you simply want to communicate outside, you can also use NAT64 to communicate with IPv4 end points and no IPv6 WAN connectivity is required.

For `wpan0` interface:

- I don't understand under what situations you see IPv6 addresses being reflected on the `wpan0` interface. In an earlier post above, you claim to see Mesh Local addresses being added to the `wpan0` interface. Yet in other posts, you claim that no Mesh Local addresses are being added. Can you clarify what configurations the Mesh Local address is being added or not?

**Comment by bahubalioffice67** [comment] 2019-01-18 06:11
I am sorry, I have modified comment now.(I don't have IPV6 on Ethernet. When I connect Ethernet(only ipv4) I am not able to see mesh and link local addresses on wpan0.)

**Comment by bahubalioffice67** [comment] 2019-01-18 06:13
All i want to do is, communicate thread device globally. (For global communication thread device needs global ip(ipv6), correct?).

**Comment by jwhui** [comment] 2019-01-18 17:44
Let me try to clarify:
- When IPv6 is available on Ethernet, you see Mesh Local and Link Local addresses reflected on the `wpan0` interface.
- When IPv6 is *not* available on Ethernet, you do *not* see Mesh Local and Link Local addresses reflected on the `wpan0` interface.

Is that correct?

**Comment by bahubalioffice67** [comment] 2019-01-21 05:08
- No
- No
When I boot up device (NCP is already connected) by default it won't show any address in wpan0

**Comment by bahubalioffice67** [comment] 2019-01-21 05:16
No
No
When I boot up device (NCP is already connected) by default it won't show any address in wpan0

**Comment by jwhui** [comment] 2019-02-01 05:19
Issue resolved by forming network and adding prefix.

**Closed by jwhui** 2019-02-01 05:19 UTC
Labels: question
