### ISSUE TITLE
Scripts in script folder doesn't work on RPi3

### ISSUE THREAD

**Issue by andredas** [openthread/borderrouter#117] opened 2017-11-15 12:06 UTC
Quick fix revert to commit 253cba0

**Comment by jwhui** [comment] 2017-11-15 14:23
@prfi, @bukepo can one of you take a look?

**Comment by prfi** [comment] 2017-11-15 20:28
I will be at work on Friday. I can take a look.

**Comment by prfi** [comment] 2017-11-17 13:47
I've tried to reproduce an issue but on my RPi3 everything is working find.

What I've done:
1. I've got an image from: https://downloads.raspberrypi.org/raspbian_lite_latest (Raspbian Stretch Lite, version: 2017-09-07)
2. I've prepared SD card and written an image to the card.
3. I've created file ssh on boot partition (to have access to RPi)
4. I've booted RPi and I've run commands: sudo su; apt-get update; apt-get install -y git
5. I've cloned this repository master branch.
6. I've run scripts "./script/bootstrap && ./script/setup" from "borderrouter" directory
7. I've changed device in "/etc/wpantund.conf": /dev/ttyUSB0 => /dev/ttyACM0

I will try to reproduce an error again on Monday. 

If you see any problems please paste more logs here then I will be able to fix an issue.

**Comment by wangnuannuan** [comment] 2017-11-20 07:32
i run the "sudo ./script/bootstrap", but it does nothing,and the same "sudo ./script/setup"

**Comment by prfi** [comment] 2017-11-20 07:35
Today I've found the root cause of this problem. I will describe it and make pull request. I guess it will be available in one hour. I want run one more test.

**Comment by prfi** [comment] 2017-11-20 08:42
I've create pull request #119 which fixes above issue.

**Comment by jwhui** [comment] 2017-11-20 18:42
Fixed by #119.

**Closed by jwhui** 2017-11-20 18:42 UTC
Labels: bug
