### ISSUE TITLE
./script/setup Failed to enable unit: File /etc/systemd/system/wpantund.service already exists. 

### ISSUE THREAD

**Issue by ghost** [openthread/borderrouter#150] opened 2018-06-15 04:39 UTC
I am following the instructions on the OpenThread Border Router Build and Configuration (https://openthread.io/guides/border-router/build) on a RPi3. 
The ./script/bootstrap went through. 
The ./script/setup gave me a lot of hard time. 

During my first several trials, the installation auto-rebooted multiple times. Finally it came to a complete. But the $sudo systemctl status shows only avahi-daemon.service is running, the rest of otbr-agent.service, otbr-web.service, and wpantund.service are not active. 
Manually $./script/server failed. 
 
I was confused, tried to rule out the reason, so I did a re-installation from formatting the sd card, changing to a 5V 2.4A power supply, setting locales to en-us, so on so forth. Then run the ./script/setup. After a long wait, it came to the error: **Failed to enable unit: File /etc/systemd/system/wpantund.service already exists.**

Does anyone see this error before? Can you share some experience? Thanks!

**Comment by leonsteenkamp** [comment] 2018-06-15 07:13
I initially ran into some issues. A few things you can check are:

- Make sure you are using the Raspbian Stretch **Lite** image
- Update it after installing Raspbian
- Rather work from the RPi3 directly for the install part. I started off ssh'ing into the Pi, but I think this messes with things.

**Comment by osrm101** [comment] 2018-06-15 17:07
@leonsteenkamp Thanks for your note. I also ip address changed and messed something like wpantund pipe when ssh. So I checked all these three points during the latest fresh re-installation.

**Comment by osrm101** [comment] 2018-06-15 17:30
I digged a little more about this error. I looked into `/etc/systemd/system/wpantund.service`. The pathes are specified to `/usr/sbin/wpantund`, but in my system, the wpantund service is at `/usr/local/sbin/wpantund`. So I edited `wpantund.service` file. Now I am able to start the wpantund service. Manually start `./script/server`, `$sudo systemctl status` shows all four required services are actively running, avahi-daemon.service, otbr-agent.service, otbr-web.service, wpantund.service. 
  `├─wpantund.service
             │ └─2086 /usr/local/sbin/wpantund -o Daemon:SetDefaultRouteForAutoAddedPrefix true -o IPv6:SetSLAACForAutoAddedPrefix true`

Now I am facing a new problem. 
`$ sudo wpanctl status`
`error: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
wpanctl: error: wpantund is either not running, locked up, or incompatible with this version of wpanctl`
There is no `wpanctl` in `/etc/systemd/system`, `/usr/sbin`, or `/usr/local/sbin`

**Comment by bukepo** [comment] 2018-06-19 03:47
@osrm101 wpanctl is located in `/usr/bin` or `/usr/local/bin`. As @leonsteenkamp suggested, the scripts are tested under Raspbian Lite image, the desktop image has more packages installed and leaves less resource for building this project, which may result in rebooting for resources being exhausted.

If you are still using the desktop version, then your new problem may also be caused by that. Because there will be two d0bus buses and somehow the *wpanctl* chooses a wrong bus.

**Comment by yz101-osrm** [comment] 2018-06-19 14:16
@bukepo Thanks for your note. 
I was using 2018-04-18-raspbian-stretch-lite image. I repeated the installation on 2018-04-18-raspbian-stretch-lite several times, these problems were very persistent. The whole issue was resolved by rolling back to 2018-03-13-raspbian-stretch-lite. I think we can close this issue.

**Comment by jwhui** [comment] 2018-06-22 23:11
I just tested a fresh install on Raspbian Stretch Lite 2018-04-18 and the border router setup on a RPi 3B Rev 1.2 and it worked for me.

With a keyboard directly attached to the RPi and Ethernet providing Internet connectivity:
```bash
$ sudo apt-get update
$ sudo apt-get install git

$ git clone https://github.com/openthread/borderrouter.git
$ cd borderrouter

$ ./script/bootstrap
$ ./script/setup
```

**Closed** 2018-07-09 09:57 UTC

**Comment by sjlongland** [comment] 2019-11-27 00:02
I hit this very issue just trying to deploy a border router… for me the work-around was to move the unit files installed by the border router to `/lib/systemd/system` instead of `/etc/systemd/system`.
